<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmudmid\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmudmid/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHmudmid.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHmudmid\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHmudmid\appProdProjectContainer([
    'container.build_hash' => 'Hmudmid',
    'container.build_id' => '6e4799bf',
    'container.build_time' => 1631091556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmudmid');
